### PR TITLE
Adapt UI to OS (LookAndFeel)

### PR DESCRIPTION
**Pull request by foreverigor**
Activate swing option for adapting the OS UL (Looks especially good on Windows) "LookAndFeel"

### CODE REVIEW

**Comment by meyerm** [comment]
Thank you for your proposal. Did you (or a friend of yours) try this patch on a OS-X machine, too? Do all dialogs or I/O widgets work for you in Windows?

**Comment by foreverigor** [comment]
On OS X/ macOS it doesn't change anything. And on Windows it basically makes minor changes to several elements — most notably the toolbar and its menu chooser, the register input fields and checkboxes adapt and look like Windows elements, which makes the interface a lot more cleaner.

So I just clicked through most of the dialogs on Windows and OS X, everything works, there should be only visual changes.

**Comment by foreverigor** [comment]
Btw, I know you (or rather, your users) have scaling issues on HiDPi screens on Windows - the elements are super small, I see this a lot with students, who use modern notebooks with high resolution displays.
Well guess what, Java 9 (Runtime) solves these issues, it activates real scaling based on Windows settings. So there is that.

**Comment by meyerm** [comment]
Okay, great - I didn't stumble upon problems with Linux, either. So I'll pull it into the development version.

**Pull request merged**
